### PR TITLE
Add Travis CI badge

### PR DESCRIPTION
**Pull request by stephanenicolas**
Following #40, there was no obvious link to CI. It's good to have that badge for this and checking the status quickly.

The build is red because master was read when the PR was created. Rebuild after #49 is merged.

### CODE REVIEW

**Comment by f2prateek** [comment]
What's the value in having this badge? Master should *always* be green - especially since we auto deploy snapshots. 

The real solution is not merge to master directly and only send PR that will automatically validate the build first.

**Comment by stephanenicolas** [comment]
The advantages are : 
* being transparent to users about the state of master
* allow us to quickly find the CI state
* allow us to quickly open CI, there was no link form Dart gihub to CI.

**Comment by stephanenicolas** [comment]
There seem to be a problem on Travis, PR is green, but branch is red... (after a rebuild)

**Comment by f2prateek** [comment]
hmm.. not sure I quite agree since

* Master should always be green and users shouldn't have to worry about the state of master
* I've never need to explicitly go check what the state of the CI was
* I've never needed to go the CI outside of a PR (which already adds a link to the build directly)

However if you think it's beneficial to your workflow and users, feel free to merge this :)

(you might need to rebase and force push to this branch to get Travis to sign off on this PR)

**Comment by stephanenicolas** [comment]
Funny @f2prateek , but I don't find the branch in my upstream remote that point this repo...
I can't rebase. I will just merge this one as it a very minor PR.

**Pull request merged**
