### PR TITLE
Issue #18: allow butterknife optional annotation usage with dart.

### PR DESCRIPTION
**Pull request by stephanenicolas**

### CODE REVIEW

**Comment by f2prateek** [comment]
I don't think this library should depend on Butterknife's annotation.

**Comment by stephanenicolas** [comment]
@f2prateek it's actually an optional dependency just to get the annotation. 

We actually need a quick resolution for that. What other solution do you prefer to see implemented ?

The only one I see is to rely on the name of the annotation, but I don't think it's as good as using ButterKnife annotation directly.

**Comment by f2prateek** [comment]
Do you really need a fork for this? You can use the fully qualified classnames if you're using both annotations.

**Comment by stephanenicolas** [comment]
Fully qualified names are so ugly.

Really, all that this fork is doing is adding a dependency that doesn't
impact your lib in any way.
How can I convince you that this PR is useful for many people ?

Maybe be saying that if it makes your lib more compliant with ButterKnife,
you can hope to get a part of its userbase, which is enormous. And there is
no reason for your lib to be less used that butterknife. But them being
incompatible or different makes your lib harder to use.

Imagine for one second that you use OptionalExtra as an annotation, in the
close world of Dart everything is easy and clean, but for devs it's a
nightmare to debug : somewhere I used butterknife.Optional instead of your
OptionalExtra, no one complains and I am stuck for a long long time before
finding the issue...

Please make it easier for devs and allow to you the same annotation for the
exact same meaning !

S.

2015-03-09 18:02 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by stephanenicolas** [comment]
And yes, we would fork for that reason, except if you make it working in a
different way.

We discovered Dart a few days ago, it works super well, it's well
implemented. Just make it easy to use with ButterKnife.

2015-03-09 18:06 GMT-07:00 Stéphane NICOLAS <steff.nicolas@gmail.com>:

**Comment by f2prateek** [comment]
Closing this, going forward we'll respect any annotation named `@Optional` (for backwards compatibility), and in the future, any annotation named `@Nullable`.

**Pull request closed without merging**
