### PR TITLE
Update to RC 2 snapshot

### PR DESCRIPTION
**Pull request by stephanenicolas**

### CODE REVIEW

**Comment by f2prateek** [comment]
You  don't need to send a PR for this, the maven release plugin will handle it.
```
mvn clean release:clean
mvn release:prepare release:perform
```

Also the next version is actually `RC1` (RC0 was the first release). Basically `x-SNAPSHOT` indicates that the next release is version `x`

**Comment by stephanenicolas** [comment]
Ok, should I try to publish the RC1 so ?

2015-07-27 16:30 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by f2prateek** [comment]
Yup! `robospice` should have access to `com.f2prateek.dart` now.

**Comment by stephanenicolas** [comment]
Cool. Can you just review / merge my last PR (the fix for inheritance)

2015-07-27 16:33 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Pull request closed without merging**
