### PR TITLE
Rename @Optional to @OptionalExtra to avoid conflicts. Closes #18

### LINKED ISSUE #18: Dart's @Optional annotation collides with butterknife.Optional
There're big chances that ButterKnife is used along Dart, and I spent 45 minutes to debug that "Optional" thing. I was using the Butterknife's annotation on my injected fields...

Because the name collides, I had to prefix those annotations with the package name, and my fields really looks ugly now.

### PR DESCRIPTION
**Pull request by f2prateek**
Will not be merged in until v2 (or at the very least 1.2), if ever.

### CODE REVIEW

**Comment by stephanenicolas** [comment]
Not sure about this one. Ideally we would have a single shared annotation between the 2 projects. This makes Dart further.

**Comment by johncarl81** [comment]
As an alternative to spur ideas... Other projects rely on the name of the annotation rather than the exact type ("Optional" in this case) to avoid conflicts,  I'm trying to remember which project did this (I was thinking Guice did this with `@Nullable`) but I can remember off the top of my head.

**Comment by stephanenicolas** [comment]
RoboGuice does this with at Nullable. But as a maintainer of RG, I didn't
like this code, it seems to be more hacking than anything else.

2015-03-09 11:39 GMT-07:00 John Ericksen <notifications@github.com>:

**Comment by johncarl81** [comment]
Yeah, I agree, it's somewhat of a hack.

Thinking about this further, why not make optional a parameter of `@InjectExtra` with a default of false, instead of a separate annotation?

**Comment by f2prateek** [comment]
@johncarl81 that last one makes most sense to me.

**Comment by stephanenicolas** [comment]
I don't want to influence you too much guys, but I think the annotation is
better.
Why, simply because it follows the butterknife usage, and this lib is
becoming a standard.

It will be easier for people to learn dart when they know butterknife.

S

2015-03-09 14:25 GMT-07:00 Prateek Srivastava <notifications@github.com>:

**Comment by f2prateek** [comment]
Closing this, going forward we'll respect any annotation named `@Optional` (for backwards compatibility), and in the future, any annotation named `@Nullable`.

**Pull request closed without merging**
