### PR TITLE
quickfix

### PR DESCRIPTION
**Pull request by dlemures**
quickfix to review

### CODE REVIEW

**Comment by johncarl81** [comment]
Hmm, this means you can't have a collection like this `Map<String, ExampleParcel>`

**Comment by dlemures** [comment]
@johncarl81 we are changing it, so if Parcelable is available, that will be possible.
However, if Parcelable is not, it won't be.

**Comment by johncarl81** [comment]
Alright.  Let me know if you need anything.

**Comment by dlemures** [comment]
@johncarl81 Should Parceler be able to Parse ArrayList<String>?
I tried to parcel it according to my last commit and it fails.

**Comment by stephanenicolas** [comment]
All tests should pass @dlemures . I hope it's not counter productive.

**Comment by stephanenicolas** [comment]
@johncarl81 If I understand well what @dlemures told me, and I could verify it myself : 

```org.parceler.Parcels.wrap(defaultKeyList)```
fails for ```List<String> defaultKeyList = new ArrayList(Arrays.asList("a", "b"));```

Is it supposed to work ?

**Comment by johncarl81** [comment]
yeah, that should absolutely work: https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/NonParcelTest.java#L74

Hmm, do you have to specify the generics like `ArrayList<String>(...)`?

**Comment by johncarl81** [comment]
Just tested this, with success:
```java
    @Test
    public void testStringList(){
        List<String> input = new ArrayList<String>();

        input.add("one");
        input.add("two");
        input.add("three");
        input.add(null);

        List<SubParcel> output = Parcels.unwrap(ParcelsTestUtil.wrap(input));
        assertEquals(4, output.size());

        assertEquals("one", output.get(0));
        assertEquals("two", output.get(1));
    }
```

**Comment by dlemures** [comment]
Issue found.... Just looking at similar error in 2014...

<parceler.version>0.2.6</parceler.version>

**Comment by johncarl81** [comment]
Oh, we introduced raw collection support later... Upgrade Parceler to 1.0.4?

**Comment by dlemures** [comment]
@johncarl81 , yes I upgraded to 1.0.4
And everything works fine. if you wanna have a look

**Comment by johncarl81** [comment]
Good to hear... let me know if anything else comes up.

**Pull request merged**
