### PR TITLE
Update Dart.java

### PR DESCRIPTION
**Pull request by yaming116**
add support `android.support.v4.app.Fragment`

### CODE REVIEW

**Comment by dlemures** [comment]
@f2prateek can we reconsider this feature?

**Comment by stephanenicolas** [comment]
How difficult would that be to create a dart for support artifact ? @dlemures

**Comment by stephanenicolas** [comment]
:+1: for me you can reopen and merge the PR. I agree with @dlemures after a private chat. Feature is powerful and few lines long. Worth it !
This should be released as 2.1.0

**Comment by stephanenicolas** [comment]
Are you OK with it @fprateek ?

**Comment by yaming116** [comment]
@stephanenicolas  I need to re-initiate a merger request?

**Comment by f2prateek** [comment]
Yeah I'm fine with it if needed. I think You'll need a rebase + add the dependencies.

**Comment by yaming116** [comment]
Well, I quickly finish it

**Pull request closed without merging**
